# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

random_walk2 <- function(niter, lambda) {
    .Call('_bios735_random_walk2', PACKAGE = 'bios735', niter, lambda)
}

armadillo_solve <- function(A, b) {
    .Call('_bios735_armadillo_solve', PACKAGE = 'bios735', A, b)
}

col_ridge2 <- function(Y, X, lambda) {
    .Call('_bios735_col_ridge2', PACKAGE = 'bios735', Y, X, lambda)
}

one_or_exp <- function(x) {
    .Call('_bios735_one_or_exp', PACKAGE = 'bios735', x)
}

